#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
HLA + PCs regression for vaccine titers (per vaccine, per gene with reference allele)

- Input vaccination TSV: contains quantitative titre columns (e.g., measles_ME_ml, rubella_ME_ml,
  diphtheria_ME_ml, HBV_antiHBsAg_ME_ml), vaccine flags (e.g., measles_vaccine_info == 1),
  and principal components PC1..PC20.

- Input HLA Excel: wide format with per-gene columns like A_1, A_2, B_1, B_2, ..., and an ID
  column named `sample_id` (can be customized).

- Model per vaccine:
    y = log1p(titer) ~ sum_{gene}(alleles_except_ref) + PCs
  where `alleles_except_ref` are allele dosage columns (0,1,2) for all alleles in a gene
  that pass the frequency threshold; the *most frequent allele within that gene* is dropped
  to serve as a reference (baseline).

- Outputs:
    out_dir/
      combined_coeffs.csv               # all vaccines stacked
      <vaccine_key>_coeffs.csv          # per-vaccine coefficients
      <vaccine_key>_design_stats.csv    # per-vaccine basic stats (N, num alleles kept, etc.)

Author: generated by ChatGPT
"""

import argparse
import math
import os
import re
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

# Statsmodels for OLS with robust SE
import statsmodels.api as sm

# -----------------------------
# Config / constants
# -----------------------------

# Mapping of vaccines and columns in TSV
DISEASES = {
    "measles": {
        "title": "Measles",
        "q_col": "measles_ME_ml",
        "vacc_flag": "measles_vaccine_info",
    },
    "rubella": {
        "title": "Rubella",
        "q_col": "rubella_ME_ml",
        "vacc_flag": "rubella_vaccine_info",
    },
    "diphtheria": {
        "title": "Diphtheria",
        "q_col": "diphtheria_ME_ml",
        "vacc_flag": "diphtheria_vaccine_info",
    },
    "HBV": {
        "title": "Hepatitis B",
        "q_col": "HBV_antiHBsAg_ME_ml",
        "vacc_flag": "HBV_vaccine_info",
    },
    # You can extend with HAV/mumps if you later have quantitative columns
}

PC_COLS = [f"PC{i}" for i in range(1, 21)]

# Regex to normalize HLA allele to chosen level
ALLELE_PATTERN = re.compile(
    r"^(?:HLA-)?([A-Z0-9]+)\*"
    r"(\d{2})"
    r"(?::([0-9A-Za-z]{1,}))?"
    r"(?::[0-9A-Za-z]{1,})*.*$",
    flags=re.IGNORECASE
)

# -----------------------------
# Helpers
# -----------------------------

def normalize_allele(allele: str, level: int = 1) -> str:
    """
    'HLA-A*01:01:01' -> 'A*01' (level=1) or 'A*01:01' (level=2).
    Keeps potential letters in the second field (e.g. 01G).
    Returns original value if pattern doesn't match or value is missing.
    """
    if not isinstance(allele, str) or allele.strip() in {"", "-", "."}:
        return allele
    m = ALLELE_PATTERN.match(allele.strip())
    if not m:
        return allele
    gene, group, protein = m.groups()
    gene = gene.upper()
    if level == 1 or not protein:
        return f"{gene}*{group}"
    else:
        return f"{gene}*{group}:{protein}"


def normalize_and_fill(hla_df: pd.DataFrame, level: int) -> pd.DataFrame:
    """
    Apply allele normalization to *_1/*_2 columns and fill '-' from the mate haplotype if possible.
    """
    df = hla_df.copy()
    gene_prefixes = sorted({c.split("_")[0] for c in df.columns if "_" in str(c)})
    for g in gene_prefixes:
        c1, c2 = f"{g}_1", f"{g}_2"
        if c1 in df.columns and c2 in df.columns:
            df[c1] = df[c1].apply(lambda x: normalize_allele(x, level) if isinstance(x, str) else x)
            df[c2] = df[c2].apply(lambda x: normalize_allele(x, level) if isinstance(x, str) else x)
            # fill '-' from mate
            m1 = df[c1] == "-"
            m2 = df[c2] == "-"
            df.loc[m1, c1] = df.loc[m1, c2]
            df.loc[m2, c2] = df.loc[m2, c1]
    return df


def process_hla_long(hla_wide: pd.DataFrame, id_col: str, level: int) -> pd.DataFrame:
    """
    Convert HLA wide to long with ID, Gene, Allele (each copy as a row).
    Drop rows where either allele is '.' for that gene.
    Duplicate homozygotes (2 copies).
    """
    if id_col not in hla_wide.columns:
        raise ValueError(f"HLA id column '{id_col}' not found in HLA table.")
    df = normalize_and_fill(hla_wide, level)
    gene_prefixes = sorted({c.split('_')[0] for c in df.columns if "_" in str(c)})
    rows = []
    for g in gene_prefixes:
        c1, c2 = f"{g}_1", f"{g}_2"
        if c1 not in df.columns or c2 not in df.columns:
            continue
        sub = df[[id_col, c1, c2]].copy()
        s1 = sub[c1].astype(str)
        s2 = sub[c2].astype(str)
        # exclude cases with '.'
        mask = (s1 != ".") & (s2 != ".")
        sub = sub.loc[mask].copy()
        if sub.empty:
            continue
        homo = sub[c1] == sub[c2]
        left = sub.loc[~homo, [id_col, c1]].rename(columns={c1: "Allele"})
        right = sub.loc[~homo, [id_col, c2]].rename(columns={c2: "Allele"})
        both = pd.concat([left, right], ignore_index=True)
        homo_df = sub.loc[homo, [id_col, c1]].rename(columns={c1: "Allele"})
        homo_df2 = pd.concat([homo_df, homo_df], ignore_index=True)  # duplicate for dose=2
        all_ = pd.concat([both, homo_df2], ignore_index=True)
        all_["Gene"] = g
        rows.append(all_)
    out = pd.concat(rows, ignore_index=True) if rows else pd.DataFrame(columns=[id_col, "Allele", "Gene"])
    out = out[(out["Allele"].notna()) & (~out["Allele"].astype(str).isin(["-", "."]))]
    out = out.rename(columns={id_col: "ID"})[["ID", "Gene", "Allele"]]
    out["ID"] = out["ID"].astype(str)
    return out


def build_allele_dose_matrix(hla_long: pd.DataFrame) -> pd.DataFrame:
    """
    Pivot long HLA to ID x Allele matrix of allele dose (0/1/2).
    """
    if hla_long.empty:
        return pd.DataFrame()
    dose = hla_long.groupby(["ID", "Allele"]).size().unstack(fill_value=0)
    dose = dose.clip(lower=0, upper=2)
    return dose


def log1p_clean(x: pd.Series) -> pd.Series:
    vals = pd.to_numeric(x, errors="coerce")
    vals = vals.where(vals >= 0)  # negative -> NaN
    return np.log1p(vals)


def detect_id_col(df: pd.DataFrame, candidates: List[str]) -> Optional[str]:
    for c in candidates:
        if c in df.columns:
            return c
    # case-insensitive
    low = {str(c).strip().lower(): c for c in df.columns}
    for c in candidates:
        if c.lower() in low:
            return low[c.lower()]
    return None


def run_regressions(
    vacc: pd.DataFrame,
    hla_wide: pd.DataFrame,
    vacc_id_candidates: List[str],
    hla_id_col: str,
    out_dir: str,
    allele_level: int = 1,
    min_freq_percent: float = 1.0,
    require_vaccinated_flag: bool = True,
) -> pd.DataFrame:
    """
    Runs OLS regression for each vaccine with quantitative titre.
    Returns the combined coefficients table.
    """
    os.makedirs(out_dir, exist_ok=True)

    vacc = vacc.copy()
    hla_wide = hla_wide.copy()

    # IDs
    vacc_id = detect_id_col(vacc, vacc_id_candidates)
    if vacc_id is None:
        raise ValueError(f"Could not find vaccination ID among {vacc_id_candidates}")
    if hla_id_col not in hla_wide.columns:
        raise ValueError(f"HLA id column '{hla_id_col}' not found in HLA table")

    vacc[vacc_id] = vacc[vacc_id].astype(str)
    hla_wide[hla_id_col] = hla_wide[hla_id_col].astype(str)

    # HLA -> long -> dose matrix
    hla_long = process_hla_long(hla_wide, id_col=hla_id_col, level=allele_level)
    dose = build_allele_dose_matrix(hla_long)
    if dose.empty:
        raise ValueError("Empty HLA allele-dose matrix after processing")

    dose.index = dose.index.astype(str)

    combined_rows = []
    design_stats = []

    for key, meta in DISEASES.items():
        q_col = meta["q_col"]
        flag_col = meta["vacc_flag"]

        if q_col not in vacc.columns:
            continue

        work = vacc.copy()

        if require_vaccinated_flag and flag_col in work.columns:
            # consider only those marked as vaccinated
            fl = work[flag_col]
            if fl.dtype == bool:
                work = work[fl]
            else:
                work = work[work[flag_col].astype(str).str.lower().isin(["1", "true", "yes", "да"])]
        # log-normalize titre
        work["log_titer"] = log1p_clean(work[q_col])
        work = work.dropna(subset=["log_titer"])

        if work.empty:
            continue

        # PCs present
        pcs_present = [c for c in PC_COLS if c in work.columns]
        # Build meta with IDs and PCs
        meta_df = work[[vacc_id] + pcs_present + ["log_titer"]].copy()
        meta_df = meta_df.rename(columns={vacc_id: "ID"})
        meta_df["ID"] = meta_df["ID"].astype(str)

        # Merge with HLA dose
        data = meta_df.merge(dose, left_on="ID", right_index=True, how="inner")
        if data.empty:
            continue

        # Keep alleles that vary (at least one carrier and one non-carrier)
        allele_cols = [c for c in data.columns if c not in (["ID", "log_titer"] + pcs_present)]
        N = len(data)
        # frequency by dose (sum dose)/(2N)
        freq_by_dose = data[allele_cols].sum() / (2.0 * N)
        freq_thr = float(min_freq_percent) / 100.0

        genes_in = sorted({a.split("*")[0] for a in allele_cols if "*" in a})
        kept_terms_total = 0

        rows_this_vacc = []

        for g in genes_in:
            g_alleles = [a for a in allele_cols if a.startswith(g + "*")]
            # apply frequency threshold
            g_keep = [a for a in g_alleles if float(freq_by_dose.get(a, 0.0)) >= freq_thr]
            if len(g_keep) < 1:
                continue
            # reference = most frequent among kept
            ref = pd.Series({a: float(freq_by_dose.get(a, 0.0)) for a in g_keep}).sort_values(ascending=False).index[0]
            g_terms = [a for a in g_keep if a != ref]

            if len(g_terms) == 0:
                continue

            cols = ["log_titer"] + g_terms + pcs_present
            df_g = data[cols].dropna().copy()
            # Drop constant predictors (no variance)
            g_terms_var = [a for a in g_terms if df_g[a].nunique() > 1]
            if len(g_terms_var) == 0 or df_g["log_titer"].nunique() < 2:
                continue

            y = df_g["log_titer"]
            X = df_g[g_terms_var + pcs_present].copy()
            X = sm.add_constant(X, has_constant="add")

            try:
                model = sm.OLS(y, X).fit(cov_type="HC3")  # robust SE
            except Exception:
                continue

            kept_terms_total += len(g_terms_var)

            for t in g_terms_var:
                coef_t = model.params.get(t, np.nan)
                pval_t = model.pvalues.get(t, np.nan)
                se_t = model.bse.get(t, np.nan)
                rows_this_vacc.append({
                    "vaccine": key,
                    "title": meta["title"],
                    "Gene": g,
                    "Allele": t,
                    "coef": float(coef_t),
                    "se": float(se_t) if pd.notna(se_t) else np.nan,
                    "p_value": float(pval_t),
                    "n": int(df_g.shape[0]),
                    "ref_allele_dropped": ref,
                    "covariates": "+".join(pcs_present) if pcs_present else "(none)",
                    "freq_ref": float(freq_by_dose.get(ref, np.nan)),
                })

        if rows_this_vacc:
            df_res = pd.DataFrame(rows_this_vacc).sort_values(["p_value", "Gene", "Allele"])
            df_res.to_csv(os.path.join(out_dir, f"{key}_coeffs.csv"), index=False)
            combined_rows.extend(rows_this_vacc)

            design_stats.append({
                "vaccine": key,
                "title": meta["title"],
                "N_obs": int(len(data)),
                "N_IDs": int(data["ID"].nunique()),
                "PCs_used": len(pcs_present),
                "allele_terms_kept": int(kept_terms_total),
                "freq_threshold_percent": float(min_freq_percent),
            })
        else:
            # still write an empty file to signal processed
            empty = pd.DataFrame(columns=[
                "vaccine","title","Gene","Allele","coef","se","p_value","n","ref_allele_dropped","covariates","freq_ref"
            ])
            empty.to_csv(os.path.join(out_dir, f"{key}_coeffs.csv"), index=False)
            design_stats.append({
                "vaccine": key,
                "title": meta["title"],
                "N_obs": int(len(data)),
                "N_IDs": int(data["ID"].nunique()),
                "PCs_used": len(pcs_present),
                "allele_terms_kept": 0,
                "freq_threshold_percent": float(min_freq_percent),
            })

    combined = pd.DataFrame(combined_rows)
    stats_df = pd.DataFrame(design_stats)

    combined.to_csv(os.path.join(out_dir, "combined_coeffs.csv"), index=False)
    stats_df.to_csv(os.path.join(out_dir, "design_stats.csv"), index=False)

    return combined


def main():
    p = argparse.ArgumentParser(description="HLA+PC regression for vaccine titers (per vaccine).")
    p.add_argument("--vacc", default="/mnt/data/all_pheno_unrel.tsv",
                   help="Vaccination TSV/CSV file with quantitative titres and PCs (default: /mnt/data/all_pheno_unrel.tsv)")
    p.add_argument("--hla", default="/mnt/data/combined_hla_out.xlsx",
                   help="HLA Excel file (wide) with sample_id and *_1/*_2 columns (default: /mnt/data/combined_hla_out.xlsx)")
    p.add_argument("--sep", default=None,
                   help="Separator for vaccination file. If omitted, guessed by extension: TSV -> '\\t', CSV -> ','.")
    p.add_argument("--vacc-id-candidates", nargs="+",
                   default=["ZLIMS ID","ZLIMS_ID","zlims_id","ID","patient_id"],
                   help="Candidate column names for sample ID in vaccination file (matched case-sensitive then case-insensitive).")
    p.add_argument("--hla-id-col", default="sample_id",
                   help="ID column in the HLA Excel file (default: sample_id).")
    p.add_argument("--allele-level", type=int, default=1, choices=[1,2],
                   help="Allele normalization level: 1 -> A*01, 2 -> A*01:01 (default: 1).")
    p.add_argument("--min-freq-percent", type=float, default=1.0,
                   help="Minimum allele frequency (by dose) in %% to keep allele in models (default: 1.0).")
    p.add_argument("--no-vacc-flag-filter", action="store_true",
                   help="Do NOT require *_vaccine_info flag == true/1 for inclusion.")
    p.add_argument("--out", default="./hla_pc_regression_out",
                   help="Output directory (default: ./hla_pc_regression_out)")

    args = p.parse_args()

    # Read vaccination file
    vacc_path = args.vacc
    sep = args.sep
    if sep is None:
        if vacc_path.lower().endswith(".tsv"):
            sep = r"\t+"  # support ragged tabs
            engine = "python"
        else:
            sep = ","
            engine = "c"
    else:
        engine = "python" if len(sep) > 1 else "c"

    vacc_df = pd.read_csv(vacc_path, sep=sep, engine=engine, encoding="utf-8")

    # Read HLA Excel
    hla_df = pd.read_excel(args.hla)

    combined = run_regressions(
        vacc=vacc_df,
        hla_wide=hla_df,
        vacc_id_candidates=args.vacc_id_candidates,
        hla_id_col=args.hla_id_col,
        out_dir=args.out,
        allele_level=args.allele_level,
        min_freq_percent=args.min_freq_percent,
        require_vaccinated_flag=not args.no_vacc_flag_filter,
    )

    print(f"Done. Wrote results to: {args.out}")
    if not combined.empty:
        print(combined.head(20).to_string(index=False))


if __name__ == "__main__":
    main()
